# This is a basic workflow that is manually triggered

name: Deploy to server

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:

# .github/workflows/my-workflow.yml
jobs:
    deployStuffYo:
        runs-on: ubuntu-latest
        steps:
                             
            - name: executing remote ssh commands using password
              uses: appleboy/ssh-action@master
              with:
                host: ${{ secrets.HOST }}
                username: ${{ secrets.USERNAME }}
                password: ${{ secrets.PASSWORD }}
                port: 22
                script: |
                 cd Staging;
                 git pull;
                 docker container rm -f staging-td;
                 docker build -t staging-td .
                 docker run --name staging-td -d -t staging-td

  
