# This is a basic workflow that is manually triggered

name: Deploy to server

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    inputs:
      prod_deploy:
        type: boolean
        description: Check this bot if this is a production deployment of the bot! Otherwise, we will only update staging.
        default: false

jobs:
    deployStuffYo:
        runs-on: ubuntu-latest
        steps:
                             
            - name: Update staging instance
              uses: appleboy/ssh-action@master
              if: ${{ !github.event.inputs.prod_deploy }}
              with:
                host: ${{ secrets.HOST }}
                username: ${{ secrets.USERNAME }}
                password: ${{ secrets.PASSWORD }}
                port: 22
                script: |
                 cd Staging;
                 git pull;
                 docker container rm -f staging-td;
                 docker build -t staging-td .
                 docker run --name staging-td -d -t staging-td

            - name: Update prod instance
              uses: appleboy/ssh-action@master
              if: ${{ github.event.inputs.prod_deploy }}
              with:
                host: ${{ secrets.HOST }}
                username: ${{ secrets.USERNAME }}
                password: ${{ secrets.PASSWORD }}
                port: 22
                script: |
                 cd Prod;
                 git pull;
                 docker container rm -f prod-td;
                 docker build -t prod-td .
                 docker run --name prod-td -d -t prod-td

  
