# This is a basic workflow that is manually triggered

name: Deploy to server

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    inputs:
      prod_deploy:
        type: boolean
        description: If a deployment is production or not.
        default: false

jobs:
    deployStuffYo:
        runs-on: ubuntu-latest
        steps:
                             
            - name: executing remote ssh commands using password
              uses: appleboy/ssh-action@master
              with:
                if: ${{ github.event.inputs.prod }}
                host: ${{ secrets.HOST }}
                username: ${{ secrets.USERNAME }}
                password: ${{ secrets.PASSWORD }}
                port: 22
                script: |
                 
                 cd Staging;
                 git pull;
                 docker container rm -f staging-td;
                 docker build -t staging-td .
                 docker run --name staging-td -d -t staging-td

  
