# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:

# .github/workflows/my-workflow.yml
jobs:
    deployStuffYo:
        runs-on: ubuntu-latest
        steps:
            - name: prepare environment
              uses: webfactory/ssh-agent@v0.7.0
              with:
                  ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
                  
                             
            - name: do stuff
              run: |
               ssh botuser@bot.sysengineer.dev ls

  
